ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING 
FINAL PROJECT - ML SUPERVISED- RANDOMFORESTREGRESSION
MERCY MWEGA NYORI


PROBLEM STATEMENT
The goal of my project is to predict the Exam score  of students based on the learning behaviors. This is important because many schools and institutions want to understand which learning behaviors lead to positive outcomes. By solving this problem, institutions will be able to provide support early, personalize learning, and supply the required resources. The data would be collected from schools' records, surveys, and online learning platforms. This is a supervised machine learning regression task where the target value is the Grade and the inputs are the learning behaviors of the students. 

DATA COLLECTION
I souces my dataset from kagglle this is my link https://www.kaggle.com/datasets/adilshamim8/student-performance-and-learning-style

DATA EXPLORATION 


Before perfroming any data exploration i will load the dataset .To avoid data leakage between the Test data and train data i performed the train_test_split to split my data into two groups. I need pandas function therefore i downloaded the library. I will also explore my dataset in terms of number or rows and columns, check the data types: whether numericals or text form, check for missing values, check for any duplicated values, check the skewns and also get the ovarall descriptive analysis of the dataset.

In [1]:
import pandas

In [2]:
pip show pandas   # 


Name: pandas
Version: 2.3.0
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: 
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2023, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contribut

In [3]:
import pandas as pd

Loading my dataset:

In [4]:
df = pd.read_csv("student_performance.csv") # loading my dataset

Looking at the first 5 rows:

In [5]:
print(df.head())

   StudyHours  Attendance  Resources  Extracurricular  Motivation  Internet  \
0          19          64          1                0           0         1   
1          19          64          1                0           0         1   
2          19          64          1                0           0         1   
3          19          64          1                1           0         1   
4          19          64          1                1           0         1   

   Gender  Age  LearningStyle  OnlineCourses  Discussions  \
0       0   19              2              8            1   
1       0   23              3             16            0   
2       0   28              1             19            0   
3       0   19              2              8            1   
4       0   23              3             16            0   

   AssignmentCompletion  ExamScore  EduTech  StressLevel  FinalGrade  
0                    59         40        0            1           3  
1               

Getting the number rows of the dataset:

In [6]:
print(len(df))      # original number of rows

14003


Getting the number of columns:

In [7]:
print(len(df.columns))  #  original number of columns

16


Before any other thing, i checked for missing values and duplicated in my dataset

In [8]:
df.isnull().sum() # checking for missing value

StudyHours              0
Attendance              0
Resources               0
Extracurricular         0
Motivation              0
Internet                0
Gender                  0
Age                     0
LearningStyle           0
OnlineCourses           0
Discussions             0
AssignmentCompletion    0
ExamScore               0
EduTech                 0
StressLevel             0
FinalGrade              0
dtype: int64

There were no missing values

In [9]:
df.duplicated()   # checking duplicates boolen

0        False
1        False
2        False
3        False
4        False
         ...  
13998    False
13999    False
14000    False
14001    False
14002    False
Length: 14003, dtype: bool

In [10]:
df.duplicated().sum() #  checking duplicates numbers

np.int64(1534)

There were no duplicates in the dataset.

installed the Scikit-learn library to be able to use the train_test_split function to splitmy dataset into 2 

In [11]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: C:\Users\hp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [12]:
from sklearn.model_selection import train_test_split

From the number of rows I had 14,000 rows so i sampled to 750 rows randomly:

In [13]:
# sample the rows 
df_sample = df.sample(n=750, random_state=42)

Since my goal is predict the Exam score of the students depending on their learning behaivours, I defined  X and y . Here the X are the independent variables, the inputs, the learning behaivours and y is the dependent varible the one we want to predict, the output which is the  ExamScore , making this Supervised learning because we have a target value. Some of the features like age, gender I dropped because they are social characterics not learning behaivours.

In [14]:
# defining the x and y and removing some columns
y = df_sample["ExamScore"]  # dependent variable
X = df_sample.drop(columns = ["Age", "Gender", "StressLevel", "ExamScore"]) # independent varibles

Choose the test size as 20% and the train as 80% and splitted the data to train and test.

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state= 42, stratify= y)                                                    

Checked fro the numberr of rows and columns of my train and test data; 750 by 12(because i dropped the features that were social characteristics)

In [16]:
X.shape

(750, 12)

In [17]:
y.shape

(750,)

Needed to understand the number data types of my columns whether they were text or numerical columns. If text then i would perform encoding to convert them to numerical so that the model can learn the patterns.

In [18]:
df.select_dtypes(include = "object").shape[1]  #  checking the data types:no text columns

0

From the above: there are 0 text columns therefore no encoding is needed.

In [19]:
df.select_dtypes(include = "number").shape[1]  # chekcing data types:numerical ones the OG 

16

From the above: all the columns in the dataset are numeric values. 

In [20]:
df.select_dtypes(include = "number").shape[1]  # chekcing data types:numerical ones sampled one

16

Performed descriptive analysis to understand the mean std the max and min. 

In [21]:
X_train.describe()             #  descriptive analysis the mean, sd and all those

,StudyHours,Attendance,Resources,Extracurricular,Motivation,Internet,LearningStyle,OnlineCourses,Discussions,AssignmentCompletion,EduTech,FinalGrade
count,600.000000,600.000000,600.000000,600.000000,600.00000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000
mean,20.275000,79.338333,1.065000,0.556667,0.91000,0.936667,1.520000,9.826667,0.593333,76.325000,0.708333,1.338333
std,5.672713,11.231092,0.705884,0.497193,0.68509,0.243765,1.088535,6.112465,0.491622,14.521622,0.454909,1.120695
min,5.000000,60.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,0.000000
25%,17.000000,69.000000,1.000000,0.000000,0.00000,1.000000,1.000000,4.750000,0.000000,64.000000,0.000000,0.000000
50%,20.000000,79.000000,1.000000,1.000000,1.00000,1.000000,2.000000,10.000000,1.000000,78.000000,1.000000,1.000000
75%,24.000000,89.000000,2.000000,1.000000,1.00000,1.000000,2.000000,15.000000,1.000000,88.250000,1.000000,2.000000
max,38.000000,100.000000,2.000000,1.000000,2.00000,1.000000,3.000000,20.000000,1.000000,100.000000,1.000000,3.000000


From the above: The mean of the study hours is 20.28 and the attendance is 79.34 whereas the max hours of study is 38 and max attendance is 100, from most students, study hours are above average and most students attendance is also above average therefore most of the students have a higher number of studying hours and their attendace is also good.


looked for variance of my features

In [22]:
X_train.var()                      # getting the variance

StudyHours               32.179674
Attendance              126.137426
Resources                 0.498272
Extracurricular           0.247201
Motivation                0.469349
Internet                  0.059421
LearningStyle             1.184908
OnlineCourses            37.362226
Discussions               0.241692
AssignmentCompletion    210.877504
EduTech                   0.206942
FinalGrade                1.255957
dtype: float64

Checked for skewness of my features;

In [24]:
# checked for the skewness distribution   interner is very left skewed and aslo edutech abit but internet is 0 -1 so o log transformation
X_train.skew()

StudyHours              0.177831
Attendance              0.094945
Resources              -0.092225
Extracurricular        -0.228709
Motivation              0.116403
Internet               -3.594671
LearningStyle          -0.028039
OnlineCourses          -0.016336
Discussions            -0.380966
AssignmentCompletion   -0.185768
EduTech                -0.918998
FinalGrade              0.169175
dtype: float64

From above the skewness are all around 0 apart from the Internet feuture (does the students have access to internet) the skewnees is -3.6 meaning its very left skewed meaning we would perform log transformation if the valuea are not (1/0) so that the skewness is even all around. But since the column is (1/0) then we will not perform log transformation.

FEATURE ENGINEERING


After exploring my dataset and knowing the insights and the picture of the dataset, I perform feature engineering. Since the range of my feature differs I performed feature scalling specificaly standadization to get the features flowing between the same ranges. All my features are numericals  therefore i will not perform Encoding.

In [23]:
#Feature enineering 
# feature scalling standizing
from sklearn.preprocessing import StandardScaler    

In [24]:
# Standadize
scaler = StandardScaler()     # scaler gives similar range to all the values


In [25]:
X_train_scaled = scaler.fit_transform(X_train)     # standadizing the trained data ,the fit takes the mean and sd from train and then stores them

In [27]:
X_test_scaled =  scaler.transform(X_test)              # standadizing the test data 

I wanted to view the first 5 rows;

In [28]:
X_train_scaled[:5]                                   # standadizing viewing

array([[-0.40137729,  0.95009128, -0.09215996, -1.12055303,  0.13147913,
         0.26003011, -1.39753745,  0.5195909 ,  0.82788481,  1.14924581,
         0.64168895, -1.19519591],
       [ 1.1864889 , -0.74305247, -0.09215996,  0.89241649,  0.13147913,
        -3.84570848,  1.36076014,  1.01080078,  0.82788481,  0.25328206,
         0.64168895, -1.19519591],
       [ 0.12791144, -0.03014984, -1.5100055 ,  0.89241649,  1.59235833,
         0.26003011, -0.47810492, -0.79030213,  0.82788481, -0.98728313,
         0.64168895,  1.48394809],
       [-0.57780686, -1.63418076, -0.09215996, -1.12055303, -1.32940007,
         0.26003011,  0.44132761,  0.02838102,  0.82788481, -0.98728313,
        -1.55838744,  0.59090009],
       [-0.57780686, -0.11926267, -0.09215996, -1.12055303,  0.13147913,
        -3.84570848, -0.47810492,  1.6657473 ,  0.82788481, -1.26296429,
        -1.55838744, -1.19519591]])

MODEL TRAINING

Since I need to learn patterns of non-linear behaivours I used Random Forest Regressor which will create decision trees across the learning outcomes  then find the average of the outputs and hence results. 

RANDOM FOREST REGRESSOR

In [29]:
from sklearn.ensemble import RandomForestRegressor

In [30]:
 # the random forest model, number of tree that are in the forest, depth to avoid overfitting
rf_regressor = RandomForestRegressor(
    n_estimators =100,
    max_depth = 6,
    random_state = 42
    )

In [31]:
rf_regressor.fit(X_train, y_train) # saves the relationships in all the 100 treesrf_regressor.fit(X_train, y_train) 

,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",6
,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""squared_error"", ""absolute_error"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""absolute_error"" for the meanabsolute error, which minimizes the L1 loss using the median of each terminalnode, and ""poisson"" which uses reduction in Poisson deviance to find splits,also using the mean of each terminal node... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 1.0 Poisson criterion... versionchanged:: 1.9 Criterion `""friedman_mse""` was deprecated.",'squared_error'
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=1.0The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None or 1.0, then `max_features=n_features`... note:: The default of 1.0 is equivalent to bagged trees and more randomness can be achieved by setting smaller values, e.g. 0.3... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to 1.0.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",1.0
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of t

In [32]:
predictions_rf = rf_regressor.predict(X_test)   # now do the exam and predict the examscore the y using the rf model in X_test

In [33]:
from sklearn.metrics import mean_absolute_error, r2_score     #  getting the mea and r2 fromsklearn library

In [34]:
mae_rf = mean_absolute_error(y_test, predictions_rf)             #  getting the mae from the predicted and the comparing them to test ones  

In [35]:
r2_rf = r2_score(y_test, predictions_rf)                # R squared coefficient the cooefficient of determination the percentage 

In [36]:
print("Evaluation")
print(f"Average error{mae_rf} points")            # the average error of during prediction
print(f"R² Score (Model strength): {r2_rf}")   # the inputs are 94% good at predicting the y / 94 % of the difference in thr grades are explained by the learning behaivours

Evaluation
Average error3.7610149010246436 points
R² Score (Model strength): 0.9359675418614151


I also used the Gradient Boosting Regression model and instead of creating independent trees like the random forest model this model creates sequential  shallow decision trees that correct the mistakes made by the trees before.The model learns from the training X and maps them on the correct answers y then learn patterns. It then creates trees and check for errors then creates a second to correct the  erros and it will do that for n times.

GRADIENT BOOSTING MODEL

In [37]:
from sklearn.ensemble import GradientBoostingRegressor

In [38]:
 # baseline settings
model = GradientBoostingRegressor(
    n_estimators  = 100,      # number of sequential trees
    learning_rate = 0.1,      # contribution of every tree 
    max_depth = 3,            # depth of the trees
    subsample = 0.8,         
    random_state = 42
)

In [39]:
model.fit(X_train, y_train)        # training the model and the fit part tries to learn the patterns it takes the x-train and maps the correct answeres ytrin then learn the patterns

,"subsample subsample: float, default=1.0The fraction of samples to be used for fitting the individual baselearners. If smaller than 1.0 this results in Stochastic GradientBoosting. `subsample` interacts with the parameter `n_estimators`.Choosing `subsample < 1.0` leads to a reduction of varianceand an increase in bias.Values must be in the range `(0.0, 1.0]`.",0.8
,"random_state random_state: int, RandomState instance or None, default=NoneControls the random seed given to each Tree estimator at eachboosting iteration.In addition, it controls the random permutation of the features ateach split (see Notes for more details).It also controls the random splitting of the training data to obtain avalidation set if `n_iter_no_change` is not None.Pass an int for reproducible output across multiple function calls.See :term:`Glossary <random_state>`.",42
,"loss loss: {'squared_error', 'absolute_error', 'huber', 'quantile'}, default='squared_error'Loss function to be optimized. 'squared_error' refers to the squarederror for regression. 'absolute_error' refers to the absolute error ofregression and is a robust loss function. 'huber' is acombination of the two. 'quantile' allows quantile regression (use`alpha` to specify the quantile).See:ref:`sphx_glr_auto_examples_ensemble_plot_gradient_boosting_quantile.py`for an example that demonstrates quantile regression for creatingprediction intervals with `loss='quantile'`.",'squared_error'
,"learning_rate learning_rate: float, default=0.1Learning rate shrinks the contribution of each tree by `learning_rate`.There is a trade-off between learning_rate and n_estimators.Values must be in the range `[0.0, inf)`.",0.1
,"n_estimators n_estimators: int, default=100The number of boosting stages to perform. Gradient boostingis fairly robust to over-fitting so a large number usuallyresults in better performance.Values must be in the range `[1, inf)`.",100
,"criterion criterion: {'friedman_mse', 'squared_error'}, default='friedman_mse'This parameter has no effect... versionadded:: 0.18.. deprecated:: 1.9 `criterion` is deprecated and will be removed in 1.11.",'deprecated'
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, values must be in the range `[2, inf)`.- If float, values must be in the range `(0.0, 1.0]` and `min_samples_split` will be `ceil(min_samples_split * n_samples)`... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, values must be in the range `[1, inf)`.- If float, values must be in the range `(0.0, 1.0)` and `min_samples_leaf` will be `ceil(min_samples_leaf * n_samples)`... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.Values must be in the range `[0.0, 0.5]`.",0.0
,"max_depth max_depth: int or None, default=3Maximum depth of the individual regression estimators. The maximumdepth limits the number of nodes in the tree. Tune this parameterfor best performance; the best value depends on the interactionof the input variables. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.If int, values must be in the range `[1, inf)`.",3
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.Values must be in the range `[0.0, inf

In [40]:
predictions = model.predict(X_test)  # predicting from unseen x-test data by passing them over the 100 trees

In [41]:
mae_gb = mean_absolute_error(y_test, predictions)      # mean squared errors checks the error/ distance btwn the actual and prediction values

In [42]:
r2_gb = r2_score(y_test, predictions)            # coeeficient of determination

In [43]:
print("Evaluation")
print(f"Average error {mae_gb}")            # the average error of during prediction
print(f"R² Score (Model strength):{r2_gb}") 

Evaluation
Average error 3.720922915682426
R² Score (Model strength):0.9350854401328124


In [44]:
print("RF predictions:", predictions_rf[:5])
print("GB predictions:", predictions[:5])

RF predictions: [46.82198835 92.96478783 91.79112911 47.58516043 75.05486027]
GB predictions: [47.55428096 93.20676809 91.82657729 47.76793793 75.88028611]


KNN MODEL

I used a last model the KNN neigbours which check the distance. It will take the most similar values and use them to make a prediction.

In [45]:
from sklearn.neighbors import KNeighborsRegressor

In [46]:
knn_model = KNeighborsRegressor(n_neighbors=5)          

In [47]:
knn_model.fit(X_train, y_train)           #  learning the patterns: giving my model my train data  fit stores the data points so that the neighbours can be looked for

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Uniform weights are used by default.See the following example for a demonstration of the impact ofdifferent weighting schemes on predictions::ref:`sphx_glr_auto_examples_neighbors_plot_regression.py`.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this isequivalent to using manhattan_distance (l1), and euclidean_distance(l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.",2
,"metric metric: str, DistanceMetric object or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.If metric is a DistanceMetric object, it will be passed directly tothe underlying computation routines.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.Doesn't affect :meth:`fit` method.",None
Name,Type,Value
"effective_metric_ effective_metric_: str or callableThe distance metric to use. It will be same as the `metric` parameteror a synonym of it, e.g. 'euclidean' if the `metric` parameter set to'minkowski' and `p` parameter set to 2.",str,'eu...an'
"effective_metric_params_ effective_metric_params_: dictAdditional keyword arguments for the metric function. For most metricswill be same with `metric_params` parameter, but may also contain the`p` parameter value if the `effective_metric_` attribute is set to'minkowski'.",dict,{}


In [48]:
predictions_knn  = knn_model.predict(X_test)       # predicting y values from unseen data 

In [49]:
mae_knn = mean_absolute_error(y_test, predictions_knn)
r2_knn = r2_score(y_test, predictions_knn)                 

In [50]:
print("KNN Evaluation")
print(f"Average error: {mae_knn} points")
print(f"R² Score: {r2_knn}")

KNN Evaluation
Average error: 14.825333333333335 points
R² Score: -0.03525425082654943


In [51]:
print("Comparison of the models")
print(f"R² Score (Random Forest regressor strength): {r2_rf}") 
print(f"R² Score (Gradient boosting regressor strength): {r2_gb}")
print(f"R² Score (KNN strength):{r2_knn}")

Comparison of the models
R² Score (Random Forest regressor strength): 0.9359675418614151
R² Score (Gradient boosting regressor strength): 0.9350854401328124
R² Score (KNN strength):-0.03525425082654943


By comparing the models by their R2, RandomForest model has the highest r2 score at 0.9359 then Gradient boosting model which follows closely at 0.9351 and KNN model which performed relatively worse at -0.3525.From this, the tree based model perform very well while the KNN. Overall, Random forest model performed the best. 

TUNING

RANDOM FOREST TUNING

In [52]:
from sklearn.model_selection import GridSearchCV

In [ ]:
parameter_grid_rf = {                    #parameter grid for rf model
     'n_estimators': [100, 200, 300],
    'max_depth': [4, 6, 8, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [ ]:
# noe go through the grid search and choose the best combinations and give me the best r2 score
grid_rf = GridSearchCV(         
    RandomForestRegressor(random_state=42),
    parameter_grid_rf,             #this are the parameters that you should go for
    cv=5,
    scoring='r2',
    n_jobs=-1
)

In [ ]:
# now do the actual tunning with x and y train then try the combinations and get the best combinations
grid_rf.fit(X_train, y_train)         

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",RandomForestR...ndom_state=42)
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'max_depth': [4, 6, ...], 'min_samples_leaf': [1, 2, ...], 'min_samples_split': [2, 5, ...], 'n_estimators': [100, 200, ...]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion <scoring_api_overview>` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'r2'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",5
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example<sphx_glr_auto_examples_model_selection_plot_grid_search_refit_callable.py>`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"ver

In [56]:
best_rf = grid_rf.best_estimator_  #  get me the best rf model with the best combinations

In [ ]:
print(f"Best Gb parameters; {best_rf}")
print(f"Best R2 Gb : {grid_rf.best_score_}")       # gives the r2 score from the best combinations

Best Gb parameters; RandomForestRegressor(max_depth=10, n_estimators=300, random_state=42)
Best R2 Gb : 0.9388367653633033


Hyperparameter tuning Improved the performance metric of Random Forest model. The MAE in Random forest was improved  from 3.761 to 3.5887 points and the R2 from 0.936 to 0.390.From this the tuned model shows that evaluation metrics have improved from the baseline model.

In [ ]:
GRADIENT BOOSTING TUNING

In [58]:
parameter_grid_gb = {          
    'n_estimators': [50, 100, 300],                # parameters that i want to try
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [2, 4, 5],
    'subsample': [0.8, 1.0]
}

In [59]:
# search for the best settings...search for the best combinations that gives the best r2 value
grid_gb = GridSearchCV(                             
    GradientBoostingRegressor(random_state=42),
    parameter_grid_gb,                            # try this settings as see what you will get
    cv=5,
    scoring='r2',
    n_jobs=-1
)

In [60]:
#  does the actual tuning check x-train and y-train with the parameters compares the r2 score and gets the best combination
grid_gb.fit(X_train,y_train)

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",GradientBoost...ndom_state=42)
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'learning_rate': [0.01, 0.05, ...], 'max_depth': [2, 4, ...], 'n_estimators': [50, 100, ...], 'subsample': [0.8, 1.0]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion <scoring_api_overview>` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'r2'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",5
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example<sphx_glr_auto_examples_model_selection_plot_grid_search_refit_callable.py>`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"verbose ve

In [61]:
best_grid_gb = grid_gb.best_estimator_   # give me the best gradient boosting model with the best parameters that you found

In [62]:
print(f"Best Gb parameters; {best_grid_gb}")
print(f"Best R2 Gb : {grid_gb.best_score_}")

Best Gb parameters; GradientBoostingRegressor(learning_rate=0.05, max_depth=2, random_state=42,
                          subsample=0.8)
Best R2 Gb : 0.9355758238107551


KNN TUNING 

In [63]:
# choosing my parameters for the grid search
parameter_grid_knn =  {
    'n_neighbors': [3, 5, 7, 9, 17, 20, 25, 38],        
    'weights': ['uniform', 'distance'],
    'p': [1, 2] 
} 
    


In [64]:
#  go through the parameters and get the best setting that produces the best r2 value
grid_knn = GridSearchCV(KNeighborsRegressor(),
    parameter_grid_knn,                #go through the parameters in this part 
    cv=5,
    scoring='r2',
    n_jobs=-1
)



In [65]:
# tune the x-train and y train with the combinations that you found and then give the best value 
grid_knn.fit(X_train,y_train)

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",KNeighborsRegressor()
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'n_neighbors': [3, 5, ...], 'p': [1, 2], 'weights': ['uniform', 'distance']}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion <scoring_api_overview>` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'r2'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",5
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example<sphx_glr_auto_examples_model_selection_plot_grid_search_refit_callable.py>`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"verbose verbose: int, default=0Controls the verbosity of info

In [66]:
best_knn_parameters = grid_knn.best_estimator_   #  give me the best knn model with the parameters that you found

In [67]:
print(f"knn Best estimators:{best_knn_parameters}")
print(f"knn Best score: {grid_knn.best_score_}")

knn Best estimators:KNeighborsRegressor(n_neighbors=7, p=1, weights='distance')
knn Best score: 0.3807566161083897


lets get the best model

In [68]:
print(f"rf best score : {grid_rf.best_score_}")
print(f"gb best score : {grid_gb.best_score_}")
print(f"knn best score : {grid_knn.best_score_}")

rf best score : 0.9388367653633033
gb best score : 0.9355758238107551
knn best score : 0.3807566161083897


From the r2 score above we see Random Forest Model performing the best with 0.9388 followed closely with Graidient Boosting with 0.9356 and KNN Model which performed relatively poorly at 0.3808. We will use Random Forest Model for the Test set.


In [70]:
prediction_best_rf = best_rf.predict(X_test)          # predict the using the x test with the best parameters that gave the besr r2 score

In [ ]:
 # evaluation metris checking the mean absolute error and cooefficient of dtermination
mae_best_rf = mean_absolute_error(y_test, prediction_best_rf)   #after mapping the x on y test get smallest distance for the actual
r2_best_rf = r2_score(y_test, prediction_best_rf) # get the best r2 score

In [74]:
print("RANDOM FOREST EVALUATION")
print(f"MAE rf: {mae_best_rf}")
print(f"R2 rf: {r2_best_rf}")

RANDOM FOREST EVALUATION
MAE rf: 3.588735561012366
R2 rf: 0.9389581809300733


From the model evaluation: the model predictions  are ,on average, 3.5887 points from the actual exam scores and this explains 0.9389 of the variation in the Exam Score of the students.

FINAL DISCUSSION

The overall pipeline involved data preprocessing and exploration, trainnig three models, hyperparameter tunning, model selection and final assessment. The supervised learning models:Random Forest Regressor, Gradient Boosting Regressor and KNN model went through  hyparameter tunning using GridsearchCv with a 5 fold-cross validation and then comparison of the model and Random Forest regressor resulted with the best R2 score of 0.9389.

MODEL STRENGTHS

Random Forest Regressor had MAE of  3.588 and R2 score of 0.9389 which are relatively high showing the model had a high performance on  the test value. The model predicted exam scores that were, on average, 3.588 points away from the actual exam scores and the model was able to explain 93.89% of the variation in the students exam scores. Moreover, in this project I used three models that were all tuned to improve performance instead of uisng tehe default settings.

LIMITATIONS

The model performance relies on the quality  and representation of the students learning behavours therefore the performance may change if a new training is used. Meaning that if the learning behaivours of the students change the performance of Random Forest Regressor will vary. 


Random Forest regressor builts complex decision trees that may be complex to explain.

RECOMMENDATIONS AND FEATURE PERFORMANCE

Checking feature importance in my dataset

In [ ]:
feature_importa = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': best_rf.feature_importances_  # rate the features
}

)

In [76]:
feature_importa = feature_importa.sort_values(
    by='Importance',
    ascending=False
)

In [78]:
print(feature_importa)

                 Feature  Importance
0             StudyHours    0.009711
1             Attendance    0.011778
2              Resources    0.002716
3        Extracurricular    0.001666
4             Motivation    0.002999
5               Internet    0.000627
6          LearningStyle    0.004812
7          OnlineCourses    0.009234
8            Discussions    0.001823
9   AssignmentCompletion    0.010566
10               EduTech    0.001369
11            FinalGrade    0.942699


The project goal is to predict the students Exam score based on their learning behaviours, and from the feature importance Final grade is the most important feature. the difference between the Exam score and Final grade is that the Exam score is continouos data while Final Grade is categorical data.Moreover, the attendance is relatively highly ranked, 0.01056 followed closely with Assignment Completion at 0.01056, then study hours at 0.00971 and Online courses at 0.009234.


RECOMMENDATIONS

From the above Model selection and feature importance to the highest Exam Score,


I would encourage students to make sure they attend all their classes, and make sure they complete all their assignements throughout their academic year and involve themselves in online courses that will give them more insights on the modules and topics. With this they will be able to get better grades. 


I would encourage schools to put class attendance policy where any attendance below the required would result to consequences and they should also reward the ones with high attendance. This will push students to attend classes and consequently better grades.


I would also encourage school to put assignment score part of the exam score so that failure to finish the assignments would result to overall failure at the end of the academic year, this will push students to finish assignments to avoid overall failure.

Moreover, school should increase online course materials to all students to have more than enough materials to learn from and gain additional information from there.

WILL I DEPLOY THE MODEL?


Yes. I will deploy my project as a desicion-tool for institutions in predicting their students Exam score from learning patterns but before deployment i would love to test the Random Forest Model Regressor through new data.

CONCLUSION

In this project, we went through data loading, descriptive analysis, data sampling and data exploration then feature engineering followed by selecting my three models and trainning them. Hyperparameter tunning using GridSearchCV, then selecting the best model and using the model for rate the feature by importance. From this, Attendance, Assignment completion, study hours and Online course were the most imformative features that influence better grades and I would encourage students to pay attentio to those learning behaivours.